# automatically generated by the FlatBuffers compiler, do not modify

# namespace: zkinterface

class Message(object):
    NONE = 0
    CircuitHeader = 1
    ConstraintSystem = 2
    Witness = 3
    Command = 4

